# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'TV Shows' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TV Shows
  pod 'MBProgressHUD'
  pod "Alamofire"
  pod 'Kingfisher', '~> 7.0'
  pod 'KeychainAccess', '~> 4.2'
  
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
               end
          end
   end
end
